#include "mapreduce.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

int main(int argc, char *argv[]) {

	if(argc < 4) {
		printf("Less number of arguments.\n");
		printf("./mapreduce #mappers #reducers inputFile\n");
		exit(0);
	}
	// ###### DO NOT REMOVE ######
	int nMappers 	= strtol(argv[1], NULL, 10);
	int nReducers 	= strtol(argv[2], NULL, 10);
	char *inputFile = argv[3];

	if(nMappers < nReducers || nMappers == 0 || nReducers == 0) {
		printf("#Mappers <= #Reducers or a value is 0\n");
		exit(0);
	}

	// ###### DO NOT REMOVE ######
	bookeepingCode();

	// ###### DO NOT REMOVE ######
	pid_t pid = fork(); //process for chunking data
	if(pid == 0){
		//send chunks of data to the mappers in RR fashion
		sendChunkData(inputFile, nMappers);
		exit(0);
	}
	sleep(1); //program stops for 1 ms

	// To do
	// spawn mappers processes and run 'mapper' executable using exec
	for(int count = 1; count <= nMappers; count++ ){
			pid_t pid2 = fork();

			if(pid2 == 0){
				char processID[5];
				sprintf(processID, "%d", count);
				char *mapperArgv[] = {"./mapper",processID,NULL};
				execvp(*mapperArgv, mapperArgv); // should not return unless there is an error, caught by exit(errno)
				exit(errno);
			} // if
			else if (pid2 == -1) { // error checking
				printf("Forking Failure\n");
				exit(1);
			} // if
	} // for

	// To do
	// wait for all children to complete execution
	int status;
	while(wait(&status) > 0);

	// ###### DO NOT REMOVE ######
    // shuffle sends the word.txt files generated by mapper
    // to reducer based on a hash function
	pid = fork();
	if(pid == 0){
		shuffle(nMappers, nReducers);
		exit(0);
	}
	sleep(1);


	// To do
	// spawn reducer processes and run 'reducer' executable using exec
	for(int count = 1; count <= nReducers; count++ ){
			pid_t pid3 = fork();

			if(pid3 == 0){
				char processID[5];
				sprintf(processID, "%d", count);
				char *reducerArgv[] = {"./reducer",processID,NULL};
				execvp(*reducerArgv, reducerArgv); // should not return unless there is an error, caught by exit(errno)
				exit(errno);
			} // if
			else if (pid3 == -1) { // error checking
				printf("Forking Failure\n");
				exit(1);
			} // if
	} // for

	// To do
	// wait for all children to complete execution
	int status2;
	while(wait(&status2) > 0);


	return 0;
}
